import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarComp from "@/components/general/Navbar";
import Footer from "@/components/general/Footer";
import GeneralModal from "@/components/general/GeneralModal";
import { ModalProvider } from "@/context/ModalContext";
import { AuthProvider } from "@/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} no-scrollbar`}>
      <body className="min-h-screen flex flex-col">
        <main className="flex-1 flex flex-col gap-16 justify-center">
          <AuthProvider>
            <ModalProvider>
              <GeneralModal />
              <NavbarComp />
              <div className="mx-auto max-w-480">{children}</div>
              <Footer />
            </ModalProvider>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
