import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import GeneralModal from "@/components/general/GeneralModal";
import { ModalProvider } from "@/context/ModalContext";
import { AuthProvider } from "@/context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BrowseLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex-1 w-full">
      {children}
    </div>
  );
}
